/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

/**
 *
 * @author User
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import java.io.File;
import java.util.ArrayList;
import Controller.NumericCriteria_Controller;
import com.sun.corba.se.impl.protocol.giopmsgheaders.Message;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import sun.security.util.Length;

public class lFrame_NumericalCriteria extends javax.swing.JInternalFrame {

    ArrayList<String> result1 = new ArrayList<String>();
    ArrayList<String> result2 = new ArrayList<String>();

    /**
     * Creates new form lFrame_NumericalCriteria
     */
    public lFrame_NumericalCriteria() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtDiscRate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtProDetails = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setTitle("Numeric Criteria");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Expected Discount Rate");

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddPro(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Add Project Details");

        txtProDetails.setToolTipText("Upload project details");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setText("Project Details");

        jButton2.setText("Select");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProDetails(evt);
            }
        });

        jButton3.setText("Submit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDone(evt);
            }
        });

        jLabel1.setText("%");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDiscRate, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButton3))
                            .addComponent(txtProDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton2))
                    .addComponent(jSeparator1))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDiscRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtProDetails, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton3))
                .addContainerGap(60, Short.MAX_VALUE))
        );

        txtDiscRate.getAccessibleContext().setAccessibleName("txtDiscRate");
        jButton1.getAccessibleContext().setAccessibleName("btnAddPro");
        txtProDetails.getAccessibleContext().setAccessibleName("txtProDetails");
        jLabel4.getAccessibleContext().setAccessibleName("lblProDetails");
        jButton2.getAccessibleContext().setAccessibleName("btnProDetails");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddPro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddPro
        // TODO add your handling code here:
        try {
            NumericCriteria_Controller NCC = new NumericCriteria_Controller();
            String file = txtProDetails.getText();

            result1 = NCC.AddProjectController(file);
            result2.add(result1.get(0));
            if(result1.isEmpty()){
            JOptionPane.showMessageDialog(null, "Sorry. The process has been failed! Please try again with correct details.");            
            }else{
            JOptionPane.showMessageDialog(null, "Project details have been added successfully.");
            }
        } catch (Exception ex) {
            Logger.getLogger(lFrame_NumericalCriteria.class.getName()).log(Level.SEVERE, null, ex);
             JOptionPane.showMessageDialog(null, "Sorry. The process has been failed! Please try again with correct details.");            
           
        }
    }//GEN-LAST:event_btnAddPro

    private void btnProDetails(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProDetails
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        chooser.showOpenDialog(null);
        File f = chooser.getSelectedFile();
        String filename = f.getName();
        String filepath = f.getPath();
        txtProDetails.setText(filepath);
    }//GEN-LAST:event_btnProDetails

    private void btnDone(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDone
        // TODO add your handling code here:
        try {
            NumericCriteria_Controller NCC = new NumericCriteria_Controller();
            String file = txtProDetails.getText();
            double DisRate = Double.parseDouble(txtDiscRate.getText());
            ArrayList<String> arrlist = NCC.CalculationController(result2, DisRate);
        } catch (Exception ex) {
            Logger.getLogger(lFrame_NumericalCriteria.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnDone
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField txtDiscRate;
    private javax.swing.JTextField txtProDetails;
    // End of variables declaration//GEN-END:variables
}
